FD_err_1 = [abs(N1_TARN_FD_BS.price-Nref_TARN_BS.price),...
    abs(N1_TARN_FD_Mer.price-Nref_TARN_Mer.price),...
    abs(N1_TARN_FD_Kou.price-Nref_TARN_Kou.price),...
    abs(N1_TARN_FD_NIG.price-Nref_TARN_NIG.price),...
    abs(N1_TARN_FD_VG.price-Nref_TARN_VG.price),...
    abs(P1_TARN_FD_BS.price-Pref_TARN_BS.price),...
    abs(P1_TARN_FD_Mer.price-Pref_TARN_Mer.price),...
    abs(P1_TARN_FD_Kou.price-Pref_TARN_Kou.price),...
    abs(P1_TARN_FD_NIG.price-Pref_TARN_NIG.price),...
    abs(P1_TARN_FD_VG.price-Pref_TARN_VG.price),...
    abs(F1_TARN_FD_BS.price-Fref_TARN_BS.price),...
    abs(F1_TARN_FD_Mer.price-Fref_TARN_Mer.price),...
    abs(F1_TARN_FD_Kou.price-Fref_TARN_Kou.price),...
    abs(F1_TARN_FD_NIG.price-Fref_TARN_NIG.price),...
    abs(F1_TARN_FD_VG.price-Fref_TARN_VG.price)];
FD_err_2 = [abs(N2_TARN_FD_BS.price-Nref_TARN_BS.price),...
    abs(N2_TARN_FD_Mer.price-Nref_TARN_Mer.price),...
    abs(N2_TARN_FD_Kou.price-Nref_TARN_Kou.price),...
    abs(N2_TARN_FD_NIG.price-Nref_TARN_NIG.price),...
    abs(N2_TARN_FD_VG.price-Nref_TARN_VG.price),...
    abs(P2_TARN_FD_BS.price-Pref_TARN_BS.price),...
    abs(P2_TARN_FD_Mer.price-Pref_TARN_Mer.price),...
    abs(P2_TARN_FD_Kou.price-Pref_TARN_Kou.price),...
    abs(P2_TARN_FD_NIG.price-Pref_TARN_NIG.price),...
    abs(P2_TARN_FD_VG.price-Pref_TARN_VG.price),...
    abs(F2_TARN_FD_BS.price-Fref_TARN_BS.price),...
    abs(F2_TARN_FD_Mer.price-Fref_TARN_Mer.price),...
    abs(F2_TARN_FD_Kou.price-Fref_TARN_Kou.price),...
    abs(F2_TARN_FD_NIG.price-Fref_TARN_NIG.price),...
    abs(F2_TARN_FD_VG.price-Fref_TARN_VG.price)];
FD_err_3 = [abs(N3_TARN_FD_BS.price-Nref_TARN_BS.price),...
    abs(N3_TARN_FD_Mer.price-Nref_TARN_Mer.price),...
    abs(N3_TARN_FD_Kou.price-Nref_TARN_Kou.price),...
    abs(N3_TARN_FD_NIG.price-Nref_TARN_NIG.price),...
    abs(N3_TARN_FD_VG.price-Nref_TARN_VG.price),...
    abs(P3_TARN_FD_BS.price-Pref_TARN_BS.price),...
    abs(P3_TARN_FD_Mer.price-Pref_TARN_Mer.price),...
    abs(P3_TARN_FD_Kou.price-Pref_TARN_Kou.price),...
    abs(P3_TARN_FD_NIG.price-Pref_TARN_NIG.price),...
    abs(P3_TARN_FD_VG.price-Pref_TARN_VG.price),...
    abs(F3_TARN_FD_BS.price-Fref_TARN_BS.price),...
    abs(F3_TARN_FD_Mer.price-Fref_TARN_Mer.price),...
    abs(F3_TARN_FD_Kou.price-Fref_TARN_Kou.price),...
    abs(F3_TARN_FD_NIG.price-Fref_TARN_NIG.price),...
    abs(F3_TARN_FD_VG.price-Fref_TARN_VG.price)];
FD_err_4 = [abs(N4_TARN_FD_BS.price-Nref_TARN_BS.price),...
    abs(N4_TARN_FD_Mer.price-Nref_TARN_Mer.price),...
    abs(N4_TARN_FD_Kou.price-Nref_TARN_Kou.price),...
    abs(N4_TARN_FD_NIG.price-Nref_TARN_NIG.price),...
    abs(N4_TARN_FD_VG.price-Nref_TARN_VG.price),...
    abs(P4_TARN_FD_BS.price-Pref_TARN_BS.price),...
    abs(P4_TARN_FD_Mer.price-Pref_TARN_Mer.price),...
    abs(P4_TARN_FD_Kou.price-Pref_TARN_Kou.price),...
    abs(P4_TARN_FD_NIG.price-Pref_TARN_NIG.price),...
    abs(P4_TARN_FD_VG.price-Pref_TARN_VG.price),...
    abs(F4_TARN_FD_BS.price-Fref_TARN_BS.price),...
    abs(F4_TARN_FD_Mer.price-Fref_TARN_Mer.price),...
    abs(F4_TARN_FD_Kou.price-Fref_TARN_Kou.price),...
    abs(F4_TARN_FD_NIG.price-Fref_TARN_NIG.price),...
    abs(F4_TARN_FD_VG.price-Fref_TARN_VG.price)];
FD_err_5 = [abs(N5_TARN_FD_BS.price-Nref_TARN_BS.price),...
    abs(N5_TARN_FD_Mer.price-Nref_TARN_Mer.price),...
    abs(N5_TARN_FD_Kou.price-Nref_TARN_Kou.price),...
    abs(N5_TARN_FD_NIG.price-Nref_TARN_NIG.price),...
    abs(N5_TARN_FD_VG.price-Nref_TARN_VG.price),...
    abs(P5_TARN_FD_BS.price-Pref_TARN_BS.price),...
    abs(P5_TARN_FD_Mer.price-Pref_TARN_Mer.price),...
    abs(P5_TARN_FD_Kou.price-Pref_TARN_Kou.price),...
    abs(P5_TARN_FD_NIG.price-Pref_TARN_NIG.price),...
    abs(P5_TARN_FD_VG.price-Pref_TARN_VG.price),...
    abs(F5_TARN_FD_BS.price-Fref_TARN_BS.price),...
    abs(F5_TARN_FD_Mer.price-Fref_TARN_Mer.price),...
    abs(F5_TARN_FD_Kou.price-Fref_TARN_Kou.price),...
    abs(F5_TARN_FD_NIG.price-Fref_TARN_NIG.price),...
    abs(F5_TARN_FD_VG.price-Fref_TARN_VG.price)];
FD_err = [mean(FD_err_1),mean(FD_err_2),mean(FD_err_3),mean(FD_err_4),mean(FD_err_5)];

FD_time_1 = [N1_TARN_FD_BS.CPU_time,...
    N1_TARN_FD_Mer.CPU_time,...
    N1_TARN_FD_Kou.CPU_time,...
    N1_TARN_FD_NIG.CPU_time,...
    N1_TARN_FD_VG.CPU_time,...
    P1_TARN_FD_BS.CPU_time,...
    P1_TARN_FD_Mer.CPU_time,...
    P1_TARN_FD_Kou.CPU_time,...
    P1_TARN_FD_NIG.CPU_time,...
    P1_TARN_FD_VG.CPU_time,...
    F1_TARN_FD_BS.CPU_time,...
    F1_TARN_FD_Mer.CPU_time,...
    F1_TARN_FD_Kou.CPU_time,...
    F1_TARN_FD_NIG.CPU_time,...
    F1_TARN_FD_VG.CPU_time];
FD_time_2 = [N2_TARN_FD_BS.CPU_time,...
    N2_TARN_FD_Mer.CPU_time,...
    N2_TARN_FD_Kou.CPU_time,...
    N2_TARN_FD_NIG.CPU_time,...
    N2_TARN_FD_VG.CPU_time,...
    P2_TARN_FD_BS.CPU_time,...
    P2_TARN_FD_Mer.CPU_time,...
    P2_TARN_FD_Kou.CPU_time,...
    P2_TARN_FD_NIG.CPU_time,...
    P2_TARN_FD_VG.CPU_time,...
    F2_TARN_FD_BS.CPU_time,...
    F2_TARN_FD_Mer.CPU_time,...
    F2_TARN_FD_Kou.CPU_time,...
    F2_TARN_FD_NIG.CPU_time,...
    F2_TARN_FD_VG.CPU_time];
FD_time_3 = [N3_TARN_FD_BS.CPU_time,...
    N3_TARN_FD_Mer.CPU_time,...
    N3_TARN_FD_Kou.CPU_time,...
    N3_TARN_FD_NIG.CPU_time,...
    N3_TARN_FD_VG.CPU_time,...
    P3_TARN_FD_BS.CPU_time ,...
    P3_TARN_FD_Mer.CPU_time,...
    P3_TARN_FD_Kou.CPU_time,...
    P3_TARN_FD_NIG.CPU_time,...
    P3_TARN_FD_VG.CPU_time,...
    F3_TARN_FD_BS.CPU_time,...
    F3_TARN_FD_Mer.CPU_time,...
    F3_TARN_FD_Kou.CPU_time,...
    F3_TARN_FD_NIG.CPU_time,...
    F3_TARN_FD_VG.CPU_time];
FD_time_4 = [N4_TARN_FD_BS.CPU_time,...
    N4_TARN_FD_Mer.CPU_time,...
    N4_TARN_FD_Kou.CPU_time,...
    N4_TARN_FD_NIG.CPU_time,...
    N4_TARN_FD_VG.CPU_time,...
    P4_TARN_FD_BS.CPU_time ,...
    P4_TARN_FD_Mer.CPU_time,...
    P4_TARN_FD_Kou.CPU_time,...
    P4_TARN_FD_NIG.CPU_time,...
    P4_TARN_FD_VG.CPU_time,...
    F4_TARN_FD_BS.CPU_time,...
    F4_TARN_FD_Mer.CPU_time,...
    F4_TARN_FD_Kou.CPU_time,...
    F4_TARN_FD_NIG.CPU_time,...
    F4_TARN_FD_VG.CPU_time];
FD_time_5 = [N5_TARN_FD_BS.CPU_time,...
    N5_TARN_FD_Mer.CPU_time,...
    N5_TARN_FD_Kou.CPU_time,...
    N5_TARN_FD_NIG.CPU_time,...
    N5_TARN_FD_VG.CPU_time,...
    P5_TARN_FD_BS.CPU_time ,...
    P5_TARN_FD_Mer.CPU_time,...
    P5_TARN_FD_Kou.CPU_time,...
    P5_TARN_FD_NIG.CPU_time,...
    P5_TARN_FD_VG.CPU_time,...
    F5_TARN_FD_BS.CPU_time,...
    F5_TARN_FD_Mer.CPU_time,...
    F5_TARN_FD_Kou.CPU_time,...
    F5_TARN_FD_NIG.CPU_time,...
    F5_TARN_FD_VG.CPU_time];
FD_time = [mean(FD_time_1),mean(FD_time_2),mean(FD_time_3),mean(FD_time_4),mean(FD_time_5)];

Conv_err_1 = [abs(N1_TARN_Conv_BS.price-Nref_TARN_BS.price),...
    abs(N1_TARN_Conv_Mer.price-Nref_TARN_Mer.price),...
    abs(N1_TARN_Conv_Kou.price-Nref_TARN_Kou.price),...
    abs(N1_TARN_Conv_NIG.price-Nref_TARN_NIG.price),...
    abs(N1_TARN_Conv_VG.price-Nref_TARN_VG.price),...
    abs(P1_TARN_Conv_BS.price-Pref_TARN_BS.price),...
    abs(P1_TARN_Conv_Mer.price-Pref_TARN_Mer.price),...
    abs(P1_TARN_Conv_Kou.price-Pref_TARN_Kou.price),...
    abs(P1_TARN_Conv_NIG.price-Pref_TARN_NIG.price),...
    abs(P1_TARN_Conv_VG.price-Pref_TARN_VG.price),...
    abs(F1_TARN_Conv_BS.price-Fref_TARN_BS.price),...
    abs(F1_TARN_Conv_Mer.price-Fref_TARN_Mer.price),...
    abs(F1_TARN_Conv_Kou.price-Fref_TARN_Kou.price),...
    abs(F1_TARN_Conv_NIG.price-Fref_TARN_NIG.price),...
    abs(F1_TARN_Conv_VG.price-Fref_TARN_VG.price)];
Conv_err_2 = [abs(N2_TARN_Conv_BS.price-Nref_TARN_BS.price),...
    abs(N2_TARN_Conv_Mer.price-Nref_TARN_Mer.price),...
    abs(N2_TARN_Conv_Kou.price-Nref_TARN_Kou.price),...
    abs(N2_TARN_Conv_NIG.price-Nref_TARN_NIG.price),...
    abs(N2_TARN_Conv_VG.price-Nref_TARN_VG.price),...
    abs(P2_TARN_Conv_BS.price-Pref_TARN_BS.price),...
    abs(P2_TARN_Conv_Mer.price-Pref_TARN_Mer.price),...
    abs(P2_TARN_Conv_Kou.price-Pref_TARN_Kou.price),...
    abs(P2_TARN_Conv_NIG.price-Pref_TARN_NIG.price),...
    abs(P2_TARN_Conv_VG.price-Pref_TARN_VG.price),...
    abs(F2_TARN_Conv_BS.price-Fref_TARN_BS.price),...
    abs(F2_TARN_Conv_Mer.price-Fref_TARN_Mer.price),...
    abs(F2_TARN_Conv_Kou.price-Fref_TARN_Kou.price),...
    abs(F2_TARN_Conv_NIG.price-Fref_TARN_NIG.price),...
    abs(F2_TARN_Conv_VG.price-Fref_TARN_VG.price)];
Conv_err_3 = [abs(N3_TARN_Conv_BS.price-Nref_TARN_BS.price),...
    abs(N3_TARN_Conv_Mer.price-Nref_TARN_Mer.price),...
    abs(N3_TARN_Conv_Kou.price-Nref_TARN_Kou.price),...
    abs(N3_TARN_Conv_NIG.price-Nref_TARN_NIG.price),...
    abs(N3_TARN_Conv_VG.price-Nref_TARN_VG.price),...
    abs(P3_TARN_Conv_BS.price-Pref_TARN_BS.price),...
    abs(P3_TARN_Conv_Mer.price-Pref_TARN_Mer.price),...
    abs(P3_TARN_Conv_Kou.price-Pref_TARN_Kou.price),...
    abs(P3_TARN_Conv_NIG.price-Pref_TARN_NIG.price),...
    abs(P3_TARN_Conv_VG.price-Pref_TARN_VG.price),...
    abs(F3_TARN_Conv_BS.price-Fref_TARN_BS.price),...
    abs(F3_TARN_Conv_Mer.price-Fref_TARN_Mer.price),...
    abs(F3_TARN_Conv_Kou.price-Fref_TARN_Kou.price),...
    abs(F3_TARN_Conv_NIG.price-Fref_TARN_NIG.price),...
    abs(F3_TARN_Conv_VG.price-Fref_TARN_VG.price)];
Conv_err_4 = [abs(N4_TARN_Conv_BS.price-Nref_TARN_BS.price),...
    abs(N4_TARN_Conv_Mer.price-Nref_TARN_Mer.price),...
    abs(N4_TARN_Conv_Kou.price-Nref_TARN_Kou.price),...
    abs(N4_TARN_Conv_NIG.price-Nref_TARN_NIG.price),...
    abs(N4_TARN_Conv_VG.price-Nref_TARN_VG.price),...
    abs(P4_TARN_Conv_BS.price-Pref_TARN_BS.price),...
    abs(P4_TARN_Conv_Mer.price-Pref_TARN_Mer.price),...
    abs(P4_TARN_Conv_Kou.price-Pref_TARN_Kou.price),...
    abs(P4_TARN_Conv_NIG.price-Pref_TARN_NIG.price),...
    abs(P4_TARN_Conv_VG.price-Pref_TARN_VG.price),...
    abs(F4_TARN_Conv_BS.price-Fref_TARN_BS.price),...
    abs(F4_TARN_Conv_Mer.price-Fref_TARN_Mer.price),...
    abs(F4_TARN_Conv_Kou.price-Fref_TARN_Kou.price),...
    abs(F4_TARN_Conv_NIG.price-Fref_TARN_NIG.price),...
    abs(F4_TARN_Conv_VG.price-Fref_TARN_VG.price)];
Conv_err_5 = [abs(N5_TARN_Conv_BS.price-Nref_TARN_BS.price),...
    abs(N5_TARN_Conv_Mer.price-Nref_TARN_Mer.price),...
    abs(N5_TARN_Conv_Kou.price-Nref_TARN_Kou.price),...
    abs(N5_TARN_Conv_NIG.price-Nref_TARN_NIG.price),...
    abs(N5_TARN_Conv_VG.price-Nref_TARN_VG.price),...
    abs(P5_TARN_Conv_BS.price-Pref_TARN_BS.price),...
    abs(P5_TARN_Conv_Mer.price-Pref_TARN_Mer.price),...
    abs(P5_TARN_Conv_Kou.price-Pref_TARN_Kou.price),...
    abs(P5_TARN_Conv_NIG.price-Pref_TARN_NIG.price),...
    abs(P5_TARN_Conv_VG.price-Pref_TARN_VG.price),...
    abs(F5_TARN_Conv_BS.price-Fref_TARN_BS.price),...
    abs(F5_TARN_Conv_Mer.price-Fref_TARN_Mer.price),...
    abs(F5_TARN_Conv_Kou.price-Fref_TARN_Kou.price),...
    abs(F5_TARN_Conv_NIG.price-Fref_TARN_NIG.price),...
    abs(F5_TARN_Conv_VG.price-Fref_TARN_VG.price)];
Conv_err = [mean(Conv_err_1),mean(Conv_err_2),mean(Conv_err_3),mean(Conv_err_4),mean(Conv_err_5)];

Conv_time_1 = [N1_TARN_Conv_BS.CPU_time,...
    N1_TARN_Conv_Mer.CPU_time,...
    N1_TARN_Conv_Kou.CPU_time,...
    N1_TARN_Conv_NIG.CPU_time,...
    N1_TARN_Conv_VG.CPU_time,...
    P1_TARN_Conv_BS.CPU_time,...
    P1_TARN_Conv_Mer.CPU_time,...
    P1_TARN_Conv_Kou.CPU_time,...
    P1_TARN_Conv_NIG.CPU_time,...
    P1_TARN_Conv_VG.CPU_time,...
    F1_TARN_Conv_BS.CPU_time,...
    F1_TARN_Conv_Mer.CPU_time,...
    F1_TARN_Conv_Kou.CPU_time,...
    F1_TARN_Conv_NIG.CPU_time,...
    F1_TARN_Conv_VG.CPU_time];
Conv_time_2 = [N2_TARN_Conv_BS.CPU_time,...
    N2_TARN_Conv_Mer.CPU_time,...
    N2_TARN_Conv_Kou.CPU_time,...
    N2_TARN_Conv_NIG.CPU_time,...
    N2_TARN_Conv_VG.CPU_time,...
    P2_TARN_Conv_BS.CPU_time,...
    P2_TARN_Conv_Mer.CPU_time,...
    P2_TARN_Conv_Kou.CPU_time,...
    P2_TARN_Conv_NIG.CPU_time,...
    P2_TARN_Conv_VG.CPU_time,...
    F2_TARN_Conv_BS.CPU_time,...
    F2_TARN_Conv_Mer.CPU_time,...
    F2_TARN_Conv_Kou.CPU_time,...
    F2_TARN_Conv_NIG.CPU_time,...
    F2_TARN_Conv_VG.CPU_time];
Conv_time_3 = [N3_TARN_Conv_BS.CPU_time,...
    N3_TARN_Conv_Mer.CPU_time,...
    N3_TARN_Conv_Kou.CPU_time,...
    N3_TARN_Conv_NIG.CPU_time,...
    N3_TARN_Conv_VG.CPU_time,...
    P3_TARN_Conv_BS.CPU_time ,...
    P3_TARN_Conv_Mer.CPU_time,...
    P3_TARN_Conv_Kou.CPU_time,...
    P3_TARN_Conv_NIG.CPU_time,...
    P3_TARN_Conv_VG.CPU_time,...
    F3_TARN_Conv_BS.CPU_time,...
    F3_TARN_Conv_Mer.CPU_time,...
    F3_TARN_Conv_Kou.CPU_time,...
    F3_TARN_Conv_NIG.CPU_time,...
    F3_TARN_Conv_VG.CPU_time];
Conv_time_4 = [N4_TARN_Conv_BS.CPU_time,...
    N4_TARN_Conv_Mer.CPU_time,...
    N4_TARN_Conv_Kou.CPU_time,...
    N4_TARN_Conv_NIG.CPU_time,...
    N4_TARN_Conv_VG.CPU_time,...
    P4_TARN_Conv_BS.CPU_time ,...
    P4_TARN_Conv_Mer.CPU_time,...
    P4_TARN_Conv_Kou.CPU_time,...
    P4_TARN_Conv_NIG.CPU_time,...
    P4_TARN_Conv_VG.CPU_time,...
    F4_TARN_Conv_BS.CPU_time,...
    F4_TARN_Conv_Mer.CPU_time,...
    F4_TARN_Conv_Kou.CPU_time,...
    F4_TARN_Conv_NIG.CPU_time,...
    F4_TARN_Conv_VG.CPU_time];
Conv_time_5 = [N5_TARN_Conv_BS.CPU_time,...
    N5_TARN_Conv_Mer.CPU_time,...
    N5_TARN_Conv_Kou.CPU_time,...
    N5_TARN_Conv_NIG.CPU_time,...
    N5_TARN_Conv_VG.CPU_time,...
    P5_TARN_Conv_BS.CPU_time ,...
    P5_TARN_Conv_Mer.CPU_time,...
    P5_TARN_Conv_Kou.CPU_time,...
    P5_TARN_Conv_NIG.CPU_time,...
    P5_TARN_Conv_VG.CPU_time,...
    F5_TARN_Conv_BS.CPU_time,...
    F5_TARN_Conv_Mer.CPU_time,...
    F5_TARN_Conv_Kou.CPU_time,...
    F5_TARN_Conv_NIG.CPU_time,...
    F5_TARN_Conv_VG.CPU_time];
Conv_time = [mean(Conv_time_1),mean(Conv_time_2),mean(Conv_time_3),mean(Conv_time_4),mean(Conv_time_5)];
figure
loglog(FD_time,FD_err,'-*','linewidth',1)
hold on
loglog(Conv_time,Conv_err,'-*','linewidth',1)
xlabel('\fontsize{12} Time (in seconds)')
ylabel('\fontsize{12} |Error|')
title('\fontsize{14} Speed and accuracy comparison')
l = legend('FD','Conv')
set(l,'Interpreter','latex','fontsize',14)

figure
loglog([250,500,1000,2000,4000],FD_time,'-*','linewidth',1)
hold on
loglog([250,500,1000,2000,4000],Conv_time,'-*','linewidth',1)
loglog([250,500,1000,2000,4000],10^-4*[250,500,1000,2000,4000].^2,':k','linewidth',1)
loglog([250,500,1000,2000,4000],10^-4*[250,500,1000,2000,4000],'-.k','linewidth',1)
xl = xlabel('$N_x$')
set(xl,'Interpreter','latex','fontsize',14)
ylabel('\fontsize{12} Time (in seconds)')
l = legend('FD','Conv','$C N_x^2$','$C N_x$','Location','southeast')
set(l,'Interpreter','latex','fontsize',14)