BS_errors = [TARN_MC_BS_3F.error, ...
    TARN_MC_BS_4F.error, ...
    TARN_MC_BS_5F.error, ...
    TARN_MC_BS_6F.error] ;
Mer_errors = [TARN_MC_Mer_3F.error, ...
    TARN_MC_Mer_4F.error, ...
    TARN_MC_Mer_5F.error, ...
    TARN_MC_Mer_6F.error] ;
Kou_errors = [TARN_MC_Kou_3F.error, ...
    TARN_MC_Kou_4F.error, ...
    TARN_MC_Kou_5F.error, ...
    TARN_MC_Kou_6F.error] ;
NIG_errors = [TARN_MC_NIG_3F.error, ...
    TARN_MC_NIG_4F.error, ...
    TARN_MC_NIG_5F.error, ...
    TARN_MC_NIG_6F.error] ;
VG_errors = [TARN_MC_VG_3F.error, ...
    TARN_MC_VG_4F.error, ...
    TARN_MC_VG_5F.error, ...
    TARN_MC_VG_6F.error] ;

plot(3:6,BS_errors,'linewidth',2)
hold on
plot(3:6,Mer_errors,'linewidth',2)
plot(3:6,Kou_errors,'linewidth',2)
plot(3:6,NIG_errors,'linewidth',2)
plot(3:6,VG_errors,'linewidth',2)
plot(3:0.01:6,0.17*1./sqrt(10.^(3:0.01:6)),'-.k','linewidth',1)
title('\fontsize{14} Monte Carlo simulations standard errors')
ylabel('\fontsize{12} Standard Error (SE)')
xlabel('\fontsize{12} log(M)')
l=legend('Black-Scholes','Merton','Kou','NIG','VG','$\frac{C}{\sqrt{M}}$');
set(l,'Interpreter','latex')