BS_errors = [   N1_TARN_MC_BS.error, ...
                N2_TARN_MC_BS.error, ...
                N3_TARN_MC_BS.error, ...
                N4_TARN_MC_BS.error,...
                N5_TARN_MC_BS.error];
Mer_errors = [  N1_TARN_MC_Mer.error, ...
                N2_TARN_MC_Mer.error, ...
                N3_TARN_MC_Mer.error, ...
                N4_TARN_MC_Mer.error,...
                N5_TARN_MC_Mer.error];
Kou_errors = [  N1_TARN_MC_Kou.error, ...
                N2_TARN_MC_Kou.error, ...
                N3_TARN_MC_Kou.error, ...
                N4_TARN_MC_Kou.error,...
                N5_TARN_MC_Kou.error];
NIG_errors = [  N1_TARN_MC_NIG.error, ...
                N2_TARN_MC_NIG.error, ...
                N3_TARN_MC_NIG.error, ...
                N4_TARN_MC_NIG.error,...
                N5_TARN_MC_NIG.error];
VG_errors = [  N1_TARN_MC_VG.error, ...
                N2_TARN_MC_VG.error, ...
                N3_TARN_MC_VG.error, ...
                N4_TARN_MC_VG.error,...
                N5_TARN_MC_VG.error];
subplot(1,3,1)     
plot(2:6,BS_errors,'linewidth',2)
hold on
plot(2:6,Mer_errors,'linewidth',2)
plot(2:6,Kou_errors,'linewidth',2)
plot(2:6,NIG_errors,'linewidth',2)
plot(2:6,VG_errors,'linewidth',2)
plot(2:0.01:6,0.13*1./sqrt(10.^(2:0.01:6)),'-.k','linewidth',1)
title('\fontsize{14} No gain')
ylabel('\fontsize{12} Standard Error (SE)')
xlab = xlabel('$\log_{10}(M)$');
set(xlab,'Interpreter','latex','fontsize',14)

BS_errors = [   P1_TARN_MC_BS.error, ...
                P2_TARN_MC_BS.error, ...
                P3_TARN_MC_BS.error, ...
                P4_TARN_MC_BS.error,...
                P5_TARN_MC_BS.error];
Mer_errors = [  P1_TARN_MC_Mer.error, ...
                P2_TARN_MC_Mer.error, ...
                P3_TARN_MC_Mer.error, ...
                P4_TARN_MC_Mer.error,...
                P5_TARN_MC_Mer.error];
Kou_errors = [  P1_TARN_MC_Kou.error, ...
                P2_TARN_MC_Kou.error, ...
                P3_TARN_MC_Kou.error, ...
                P4_TARN_MC_Kou.error,...
                P5_TARN_MC_Kou.error];
NIG_errors = [  P1_TARN_MC_NIG.error, ...
                P2_TARN_MC_NIG.error, ...
                P3_TARN_MC_NIG.error, ...
                P4_TARN_MC_NIG.error,...
                P5_TARN_MC_NIG.error];
VG_errors = [  P1_TARN_MC_VG.error, ...
                P2_TARN_MC_VG.error, ...
                P3_TARN_MC_VG.error, ...
                P4_TARN_MC_VG.error,...
                P5_TARN_MC_VG.error];
subplot(1,3,2)
plot(2:6,BS_errors,'linewidth',2)
hold on
plot(2:6,Mer_errors,'linewidth',2)
plot(2:6,Kou_errors,'linewidth',2)
plot(2:6,NIG_errors,'linewidth',2)
plot(2:6,VG_errors,'linewidth',2)
plot(2:0.01:6,0.14*1./sqrt(10.^(2:0.01:6)),'-.k','linewidth',1)
title('\fontsize{14} Part gain')
ylabel('\fontsize{12} Standard Error (SE)')
xlab = xlabel('$\log_{10}(M)$');
set(xlab,'Interpreter','latex','fontsize',14)

BS_errors = [   F1_TARN_MC_BS.error, ...
                F2_TARN_MC_BS.error, ...
                F3_TARN_MC_BS.error, ...
                F4_TARN_MC_BS.error,...
                F5_TARN_MC_BS.error];
Mer_errors = [  F1_TARN_MC_Mer.error, ...
                F2_TARN_MC_Mer.error, ...
                F3_TARN_MC_Mer.error, ...
                F4_TARN_MC_Mer.error,...
                F5_TARN_MC_Mer.error];
Kou_errors = [  F1_TARN_MC_Kou.error, ...
                F2_TARN_MC_Kou.error, ...
                F3_TARN_MC_Kou.error, ...
                F4_TARN_MC_Kou.error,...
                F5_TARN_MC_Kou.error];
NIG_errors = [  F1_TARN_MC_NIG.error, ...
                F2_TARN_MC_NIG.error, ...
                F3_TARN_MC_NIG.error, ...
                F4_TARN_MC_NIG.error,...
                F5_TARN_MC_NIG.error];
VG_errors = [  F1_TARN_MC_VG.error, ...
                F2_TARN_MC_VG.error, ...
                F3_TARN_MC_VG.error, ...
                F4_TARN_MC_VG.error,...
                F5_TARN_MC_VG.error];
subplot(1,3,3)
plot(2:6,BS_errors,'linewidth',2)
hold on
plot(2:6,Mer_errors,'linewidth',2)
plot(2:6,Kou_errors,'linewidth',2)
plot(2:6,NIG_errors,'linewidth',2)
plot(2:6,VG_errors,'linewidth',2)
plot(2:0.01:6,0.15*1./sqrt(10.^(2:0.01:6)),'-.k','linewidth',1)
title('\fontsize{14} Full gain')
ylabel('\fontsize{12} Standard Error (SE)')
xlab = xlabel('$\log_{10}(M)$');
set(xlab,'Interpreter','latex','fontsize',14)
suptitle('\fontsize{14} Monte Carlo simulations standard errors')

l=legend('Black-Scholes','Merton','Kou','NIG','VG','$\frac{C}{\sqrt{M}}$');
set(l,'Interpreter','latex','fontsize',12)