BS_errors = [TARN_MC_BS_3P.error, ...
    TARN_MC_BS_4P.error, ...
    TARN_MC_BS_5P.error, ...
    TARN_MC_BS_6P.error] ;
Mer_errors = [TARN_MC_Mer_3P.error, ...
    TARN_MC_Mer_4P.error, ...
    TARN_MC_Mer_5P.error, ...
    TARN_MC_Mer_6P.error] ;
Kou_errors = [TARN_MC_Kou_3P.error, ...
    TARN_MC_Kou_4P.error, ...
    TARN_MC_Kou_5P.error, ...
    TARN_MC_Kou_6P.error] ;
NIG_errors = [TARN_MC_NIG_3P.error, ...
    TARN_MC_NIG_4P.error, ...
    TARN_MC_NIG_5P.error, ...
    TARN_MC_NIG_6P.error] ;
VG_errors = [TARN_MC_VG_3P.error, ...
    TARN_MC_VG_4P.error, ...
    TARN_MC_VG_5P.error, ...
    TARN_MC_VG_6P.error] ;

plot(3:6,BS_errors,'linewidth',2)
hold on
plot(3:6,Mer_errors,'linewidth',2)
plot(3:6,Kou_errors,'linewidth',2)
plot(3:6,NIG_errors,'linewidth',2)
plot(3:6,VG_errors,'linewidth',2)
plot(3:0.01:6,0.15*1./sqrt(10.^(3:0.01:6)),'-.k','linewidth',1)
title('\fontsize{14} Monte Carlo simulations standard errors')
ylabel('\fontsize{12} Standard Error (SE)')
xlabel('\fontsize{12} log(M)')
l=legend('Black-Scholes','Merton','Kou','NIG','VG','$\frac{C}{\sqrt{M}}$');
set(l,'Interpreter','latex')